module VoipApi

  # A VILocation defines data that is stored in our database for a location registered to a DID.
  # @attr [String] location_id ID generated by 911 provider (DASH) associated with the location
  # @attr [String] address1 Street and house number
  # @attr [String] address2 Any additional address information such as 'Apt 1' or 'STE 100'
  # @attr [String] city City or community Name
  # @attr [String] state Two letter state abbreviation
  # @attr [String] zip_code 5-digit ZIP code
  # @attr [String] plus_four 4-digit ZIP code extension
  # @attr [String] caller_name Caller Name
  # @attr [String] latitude Latitudinal Coordinates
  # @attr [String] longitude Longitudinal Coordinates
  # @attr [String] activated_time Date in which the location was provisioned
  # @attr [String] update_time Date in which the location was last updated
  # @attr [String] status_code GEOCODED or PROVISIONED. Old locations may be VERIFIED or UNVERIFIED
  # @attr [String] status_description Describes the status code
  # @see VoipApi::API::X911Request#get_locations
  class VILocation
    attr_accessor :location_id, :address1, :address2, :city, :state, :zip_code, :plus_four, :caller_name, :latitude, :longitude, :activated_time, :update_time, :status_code, :status_description

    # @!visibility private
    def initialize(hashie_params={})
      # Setup all our attributes if we respond to it.
      hashie_params.each do |k, v|
        instance_variable_set("@#{k}", v) unless v.nil?
      end
    end

    # Describes the attribute passed in
    # @param attribute [Symbol] A symbol representing the attribute for which you desire a description of
    def self.description(attribute)
      case attribute
      when :location_id
        "ID generated by 911 provider (DASH) associated with the location"
      when :address1
        "Street and house number"
      when :address2
        "Any additional address information such as 'Apt 1' or 'STE 100'"
      when :city
        "City or community Name"
      when :state
        "Two letter state abbreviation"
      when :zip_code
        "5-digit ZIP code"
      when :plus_four
        "4-digit ZIP code extension"
      when :caller_name
        "Caller Name"
      when :latitude
        "Latitudinal Coordinates"
      when :longitude
        "Longitudinal Coordinates"
      when :activated_time
        "Date in which the location was provisioned"
      when :update_time
        "Date in which the location was last updated"
      when :status_code
        "GEOCODED or PROVISIONED. Old locations may be VERIFIED or UNVERIFIED"
      when :status_description
        "Describes the status code"
      end
    end
  end
  
end
